/*
 * Copyright 2024-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.assistant.agent.core.model;

import com.alibaba.assistant.agent.common.enums.Language;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents a piece of generated code.
 * This is the core data model for storing code generated by LLM.
 *
 * @author Spring AI Alibaba
 * @since 1.0.0
 */
public class GeneratedCode implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Unique function name (used as identifier)
	 */
	private String functionName;

	/**
	 * Programming language
	 */
	private Language language;

	/**
	 * The actual code content (function implementation only)
	 */
	private String code;

	/**
	 * Natural language description of what this function does
	 */
	private String description;

	/**
	 * Generation timestamp
	 */
	private LocalDateTime createdAt;

	/**
	 * Last modification timestamp
	 */
	private LocalDateTime updatedAt;

	/**
	 * Original user query that triggered this code generation
	 */
	private String originalQuery;

	/**
	 * Function parameters specification (e.g., ["param1", "param2"] or ["param1: str", "param2: int"])
	 * This helps ensure consistency between code generation and execution
	 */
	private java.util.List<String> parameters;

	/**
	 * Function signature for documentation and validation
	 * Example: "calculate_sum(a: int, b: int) -> int"
	 */
	private String functionSignature;

	public GeneratedCode() {
		this.createdAt = LocalDateTime.now();
		this.updatedAt = LocalDateTime.now();
		this.parameters = new java.util.ArrayList<>();
	}

	public GeneratedCode(String functionName, Language language, String code, String description) {
		this();
		this.functionName = functionName;
		this.language = language;
		this.code = code;
		this.description = description;
	}

	// Getters and Setters

	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public Language getLanguage() {
		return language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
		this.updatedAt = LocalDateTime.now();
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getOriginalQuery() {
		return originalQuery;
	}

	public void setOriginalQuery(String originalQuery) {
		this.originalQuery = originalQuery;
	}

	public java.util.List<String> getParameters() {
		return parameters;
	}

	public void setParameters(java.util.List<String> parameters) {
		this.parameters = parameters;
	}

	public String getFunctionSignature() {
		return functionSignature;
	}

	public void setFunctionSignature(String functionSignature) {
		this.functionSignature = functionSignature;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		GeneratedCode that = (GeneratedCode) o;
		return Objects.equals(functionName, that.functionName) &&
				language == that.language;
	}

	@Override
	public int hashCode() {
		return Objects.hash(functionName, language);
	}

	@Override
	public String toString() {
		return "GeneratedCode{" +
				"functionName='" + functionName + '\'' +
				", language=" + language +
				", description='" + description + '\'' +
				", createdAt=" + createdAt +
				'}';
	}
}

